name: fit_quest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' 

# The minimum Flutter version your project supports.
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  latlong2: ^0.8.0 # Continue using latlong2 for working with coordinates
  geolocator: ^9.0.0 
  google_maps_flutter: ^2.1.1 # Use the latest version available
  geocoding: ^2.1.0 # Continue using geolocator for location access
  permission_handler: ^10.2.0
  cloud_firestore: ^5.5.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.9
  sqflite_common_ffi: ^2.0.0
  flutter_animate: ^4.1.3

  # Add other dependencies here (if any)
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.2
  mockito: ^5.0.17
  build_runner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # Enables the use of Material Design icons in your project.
  uses-material-design: true

  # Asset declarations
  assets:
    - assets/intermediate/
    - assets/medium/
    - assets/Bak6rN.jpg
    - assets/forest1.jpg
    - assets/forest2.jpg
    - assets/forest3.jpg
    - assets/forest4.jpg
    - assets/forest5.jpg
    - assets/forest6.jpg
    - assets/intermediate/burpee.gif
    - assets/intermediate/hand_realease_push_up.gif
    - assets/intermediate/jumping_jack.gif
    - assets/intermediate/lunges.gif
    - assets/intermediate/mountain_climber.gif
    - assets/intermediate/plank.gif
    - assets/intermediate/side_squat.gif
    - assets/intermediate/sit-ups.gif
    - assets/medium/agility_ball_throw.gif
    - assets/medium/air_bike.gif
    - assets/medium/alternate_bicep_curls.gif
    - assets/medium/around_the_world_superman.gif

